[general]
# must be one of "error", "warning", "info" or "debug"
debug = "info"

# worker_type must be one of "releasing" or "recording"
# if you use type "recording", you can omit all other sections
# except for C3Tracker
worker_type = "releasing"

# operation mode must be one of "loop_until_empty", "loop_forever" or
# "single" (default).
#   loop_until_empty: process all available tickets until none are available,
#                     then exit cleanly
#   loop_forever: loop forever. wait two seconds if a ticket was processed,
#                 30 seconds if no ticket was found
#   single: process a single ticket, then exit.
run_mode = "single"

[C3Tracker]
url = "https://tracker.c3voc.de/"
# create a https://tracker.c3voc.de/workers or use https://tracker.c3voc.de/workers/group/92/edit
# and add Token and Secret here:
group = "<group>"
secret = "<secret>"
#only set host if you don't want to use local machine name
#host = "my-machine-name"

[download.workers]
# list all available download tools here. Use whatever you want, as long
# as it supports directly downloading to a specific file name.
python = true # the value of this does not matter
wget = ["wget", "-q", "-O", "--TARGETPATH--", "--", "--DOWNLOADURL--"]


[voctoweb]

# "enable_default" below specifies the behaviour if the `Publishing.<service>.Enable`
# property is missing in a ticket. If "yes", using the service is enabled,
# otherwise it"s disabled.
enable_default = true

api_url = "https://media.ccc.de/api/" # with trailing slash!
api_key = "<voctoweb key>"

# for building urls e.g. in social media posts, webhooks, etc. - no trailing slashes!
frontend_url = "https://media.ccc.de"
cdn_url = "https://cdn.media.ccc.de"
static_url = "https://static.media.ccc.de"

# instance name is the name you refer to you're instead with, it's used for the tweets / toots
instance_name = "media.ccc.de"

#ssh_host = "<host to release files to>"
#ssh_port = "<ssh port on the release host>"
#ssh_user = "<ssh user on the release host>"

[youtube]
secret = "<youtube-api-secret>"
client_id = "<youtube-client-id>"

[twitter]
token = "<user token>"
token_secret = "<user secret>"
consumer_key = "<consumer key>"
consumer_secret = "<consumer secret>"

[mastodon]
api_base_url = "https://mastodon.social" # no trailing slash
email = "<loginemail>"
password = "<password>"

[bluesky]
username = "<username>"
app_password = "<app password>"

[rclone]
exe_path = "/path/to/rclone/binary"
config_path = "/path/to/rclone/config"

[defaults]
# For some properties, you can define defaults which get used if the
# property is not found in the ticket itself. Note that the property being
# empty in the ticket does also trigger a fallback to the default.
"Publishing.Bluesky.Enable" = true
"Publishing.Mastodon.Enable" = true
"Publishing.Rclone.Enable" = false
"Publishing.Twitter.Enable" = false
"Publishing.Voctoweb.Enable" = true
#"Publishing.RewriteSlug.Enabled" = true
"Publishing.YouTube.Enable" = false
"Publishing.YouTube.Privacy" = "private"
"Record.DownloadHelper" = "python"
